name: Build & Deploy

on:
  push:
    branches:
    - deploy

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Env Setup
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Create Production Build
        run: npm run build --prod
        env: 
          CI : false
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
